name: .NET Core CI # Name of workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: XUnit Viewer
      uses: AutoModality/action-xunit-viewer@v1.0.1
      if: always()
      with:
        results: ${{ env.RESULTS_PATH }}
    - name: The generated report
      run: echo "The report is ${{ steps.xunit-viewer.outputs.report-file }}" 
      if: always()   
    - name: Attach the report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: alternate-results-path-reports
        path: ${{ env.RESULTS_PATH }}
